# -*- coding: utf-8 -*-
import json, sys
from facts_common import *
F = dict(
 callout='<strong>Update 01.10. — Komplett-Check von Shop und Printify abgeschlossen:</strong> Alle 69 Punkte neu bewertet, 6 neue dazu; die Etiketten oben zeigen „Teilweise“ und „Mit OFE&nbsp;v3“. <strong>Wichtigster Befund:</strong> Printify hatte seine Versandprofile überschrieben, der Checkout hätte 23,19&nbsp;€ pro Poster verlangt. <strong>Von Claude behoben und geprüft:</strong> automatischer Gratisversand für Deutschland (Probeberechnung 0&nbsp;€), Testcode LAUNCH-TEST-100 damit kombinierbar (Testbestellung 0,00&nbsp;€), „Favoriten“ statt „Bestseller“, Kontakt-Link, Rahmen- und Größenangaben, GRIT und ICONS im Menü, alle 3.264 Produktbilder mit Alt-Text, OFE&nbsp;v3 ohne Ferrari und Messi auf der Startseite und mit Cookie-Link. <strong>Deine Reihenfolge:</strong> Richtlinien einfügen → Zahlarten → Testbestellung → OFE&nbsp;v3 veröffentlichen → Passwort raus.',
 footer_stand='Stand: 1. Oktober 2026 · Komplett-Check von Shop und Printify mit Versand-Fix (29.09.–01.10.)',
 b2=B2, b7=B7,
 b3_extra=' Seit 29.09. zeigen auch die Bausteine für „inkl. Steuern“ und „inkl. Zölle“ den §&nbsp;19-Text, falls Shopify sie je einblendet.',
 b10=B10 + 'Seit 29.09. zusätzlich: Startseite ohne Ferrari- und Messi-Motiv, „Favoriten“ statt „Bestseller“, Link zu den Cookie-Einstellungen, Erstattungs-FAQ passend zur Widerrufsbelehrung. Achtung bei der Auswahl: Die ältere Arbeitskopie heißt jetzt „ARCHIV – OFE v3 WIP (nicht veröffentlichen)“. Dauer: ~5 Minuten.',
 b10_pick='(nicht „ARCHIV – OFE v3 WIP“)',
 r6='Der Shopify-Cookie-Banner ist aktiv: Das Banner-Skript wird live ausgeliefert, am 25.08. erschien er deutsch. <strong>Neu 29.09.:</strong> Die Datenschutzerklärung verspricht einen Footer-Link zum Ändern der Einwilligung. In OFE&nbsp;v3 führte „Datenschutz-Einstellungen“ auf Shopifys US-Opt-out-Seite. Claude hat in OFE&nbsp;v3 eingebaut, dass dieser Link jetzt die Cookie-Einstellungen öffnet; klappt das einmal nicht, führt er wie bisher zur Opt-out-Seite. Bleibt für dich: nach dem OFE-v3-Publish im privaten Fenster testen, ob Banner und Link funktionieren.',
 s2='Die Menüs für OFE&nbsp;v3 sind vollständig (Hauptmenü, footer-shop, footer-info, footer-hilfe), alle Links funktionieren. Seit 29.09. stehen auch GRIT und ICONS im Untermenü „Kollektionen“, und der Menüpunkt heißt „Favoriten“ statt „Bestseller“ (am 30.09. unabhängig geprüft: nichts verloren, keine Dubletten). Das Live-Theme v2.0 zeigt keine Footer-Menüs; das erledigt sich mit dem OFE-v3-Publish, dann abhaken. Optional: Dubletten zwischen footer-info und footer-hilfe bereinigen (sag Bescheid).',
 p2_done=True, p2_tags=[],
 p2='✓ Von Claude ergänzt (29.09.–01.10.): Alle 3.264 Produktbilder haben jetzt einen Alt-Text, vorher fehlten 2.474. Schema: Produkttitel, dazu Rahmenfarbe und Größe in cm, wenn das Bild zu einer Variante gehört, sonst „gerahmtes Poster – Ansicht N“. Am 01.10. nachgezählt: 0 Bilder ohne Alt-Text. Neue Printify-Produkte bringen wieder Bilder ohne Alt-Text mit, das übernimmt Claude beim Konventions-Check.',
 p4='In allen Beschreibungen stehen cm-Angaben; seit 29.09. nennen auch alle 14 Querformat-Produkte die Größen richtig als Breite × Höhe. Offen: Die Variantenauswahl zeigt noch Zoll und englische Optionsnamen („Size“, „Color“, „Black/White“), die kommen von Printify. Umstellen am sichersten in Printify, sonst überschreibt der nächste Sync die Änderung.',
 pn3=PN3,
 pn5='Stand 29.09.: <strong>19 Produkte</strong> nennen eine Marke oder Person direkt (u.&nbsp;a. Batman, Ferrari/F1, Marlboro, Porsche, Nike „Just Do It“, Wimbledon, Godfather, Messi, Ronaldo, Neymar, Jordan), dazu rund 15 Motive mit Promi-Bezug in den Tags. 5 davon liegen in der Favoriten-Collection. Seit 29.09. zeigt die OFE-v3-Startseite statt Ferrari und Messi eigene Motive (FOCUS-Skulptur, Queens-Leopard). Noch drin: im Raum „Büro“ das Vintage-Formula-1-Motiv, und die Seite „Raum-Inspiration“ nutzt weiter Messi. Ohne Lizenz ist das in Deutschland ein typischer Abmahngrund, und Printify kann solche Produkte sperren. Deine Entscheidung je Motiv: behalten, umbenennen oder entfernen. Entwurf-Status setzen oder aus Collections nehmen übernimmt Claude. Keine Rechtsberatung: im Zweifel fachlich prüfen lassen.',
 pn1='Hat nur 3 Größen (alle 2:3) statt 6. Am 29.09. hat Claude den SEO-Text von „viele Größen“ auf „drei Größen“ korrigiert; die Größenzeile stimmt. Bleibt nur deine Entscheidung: in Printify 11×14, 16×20 und 18×24 ergänzen oder bei 3 Größen bleiben (dann abhaken).',
 pn2=PN2,
 pn2_howto_b='(GRIT und ICONS stehen seit 29.09. im Kollektionen-Menü.)',
 pn6='✓ Von Claude erledigt (29.09.) und am 30.09. unabhängig geprüft: 12 Collection-Texte sagen jetzt „Rahmen in Schwarz oder Weiß“ statt nur „schwarzer Rahmen“; 11 Querformat-Produkte nennen die Größen als Breite × Höhe; Größen-Guide und FAQ nutzen dieselben ganzen cm-Werte wie Theme und Produkte; der kaputte Link „Schreib uns“ auf „Über uns“ führt jetzt zur Kontaktseite.',
 tb1='✓ In OFE&nbsp;v3 ist die kuratierte Collection auf Startseite, Hero, 404, Warenkorb, Gallery Wall und im Hauptmenü verlinkt. Seit 29.09. heißen Überschriften und Buttons „Unsere Favoriten“, „Favoriten ansehen“ und „FAVORITEN“ statt „Bestseller“; die Adresse bleibt gleich.',
 t3_extra=' Die ältere Arbeitskopie heißt seit 29.09. „ARCHIV – OFE v3 WIP (nicht veröffentlichen)“, damit du beim Publish nicht das falsche Theme erwischst.',
 tn3='✓ Von Claude erledigt (29.09.), am 30.09. unabhängig geprüft, live mit dem Publish: Editorial-Bereich und Raum-Inspiration „Wohnzimmer“ zeigen eigene Motive statt Ferrari und Messi; „Favoriten“ statt „Bestseller“; Footer-Link „Datenschutz-Einstellungen“ öffnet die Cookie-Einstellungen; FAQ-Antwort zur Erstattung passt zur Widerrufsbelehrung; Steuer-Bausteine für „inkl. Steuern/Zölle“ auf §&nbsp;19; theme-color gesetzt. Hinweis aus der Prüfung: Der Editorial-Block hat keine eigenen Zahlen hinterlegt. Prüf im Theme-Editor, ob dort „99 kuratierte Motive“ steht, aktuell sind es 113.',
)
json.dump(F, open(sys.argv[1],'w',encoding='utf-8'), ensure_ascii=False, indent=1)
print('facts ok')
